//! Firestore persistence for completed simulation runs.
//!
//! Mirrors the `Option<FirestoreDb>` no-op-when-`None` pattern in
//! `crate::backend::firestore`: when the server is started with
//! `FIRESTORE_DATABASE_ID=debug`, the db handle is `None` and we just
//! log instead of writing anything. Records live under the
//! `simulation_runs` collection, keyed by a fresh run id.

use firestore::FirestoreDb;
use log::{debug, error, warn};
use serde::{Deserialize, Serialize};

use crate::backend::firestore::FirestoreError;
use crate::simulator::types::{SimulationParams, SimulationResult, SimulationStep};

/// Firestore collection for stored simulation runs.
const RUNS_COLLECTION: &str = "simulation_runs";

/// One persisted simulation run. Stored verbatim — params, every step,
/// and the final result — so a future "view past run" UI can replay
/// the run without re-executing it.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimulationRunRecord {
    /// Document id and primary key. Format: `"<DDD-YYYY>-<rand_hex>"` —
    /// readable enough that listing the collection sorts roughly by date
    /// while still being unique. Generated by [`new_run_id`].
    pub run_id: String,
    /// Wall-clock UTC timestamp the run finished. Stored as an ISO-8601
    /// string to keep the Firestore schema simple (no `chrono` types
    /// reaching the serializer).
    pub timestamp: String,
    /// Inputs supplied by the client.
    pub params: SimulationParams,
    /// Every emitted step, in order.
    pub steps: Vec<SimulationStep>,
    /// Final result tally.
    pub result: SimulationResult,
}

/// Mint a new run id. Combines the in-game start date (so listing by id
/// roughly orders runs by simulation date) with a short random hex
/// suffix from `rand` for uniqueness.
pub fn new_run_id(params: &SimulationParams) -> String {
    use rand::Rng;
    let mut rng = rand::rng();
    let suffix: u32 = rng.random();
    format!("{}-{:08x}", params.start_date.format(), suffix)
}

/// Format the current wall-clock time as a sortable ISO-8601-ish string
/// `"YYYY-MM-DDTHH:MM:SSZ"` without pulling in `chrono`. Falls back to
/// just the seconds-since-epoch on the very rare clock-error case.
pub fn now_iso_timestamp() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(d) => d.as_secs() as i64,
        Err(e) => return format!("err-{}", e.duration().as_secs()),
    };
    // Days from epoch (1970-01-01) using a simple algorithm valid for
    // 1970..2400. The civil-from-days routine is standard.
    let days_from_epoch = secs.div_euclid(86_400);
    let secs_of_day = secs.rem_euclid(86_400);
    let h = secs_of_day / 3600;
    let m = (secs_of_day / 60) % 60;
    let s = secs_of_day % 60;

    let (y, mo, d) = civil_from_days(days_from_epoch);
    format!("{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z", y, mo, d, h, m, s)
}

/// Howard Hinnant's "civil from days" algorithm. Converts days since
/// 1970-01-01 to (year, month, day). Valid across the range we care
/// about (well past year 2400).
fn civil_from_days(days: i64) -> (i32, u32, u32) {
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = (z - era * 146_097) as u64; // [0, 146096]
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365; // [0, 399]
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let d = doy - (153 * mp + 2) / 5 + 1; // [1, 31]
    let m = if mp < 10 { mp + 3 } else { mp - 9 }; // [1, 12]
    let y = if m <= 2 { y + 1 } else { y };
    (y as i32, m as u32, d as u32)
}

/// Save `record` to the `simulation_runs` collection. No-op when the
/// db handle is `None` (debug mode).
pub async fn save_simulation_run(
    db: &Option<FirestoreDb>,
    record: &SimulationRunRecord,
) -> Result<(), FirestoreError> {
    debug!(
        "Firestore: saving simulation run {} ({} steps)",
        record.run_id,
        record.steps.len()
    );

    match db {
        None => {
            warn!("Firestore: skipping simulation save (debug mode)");
            Ok(())
        }
        Some(db) => {
            let result = db
                .fluent()
                .update()
                .in_col(RUNS_COLLECTION)
                .document_id(&record.run_id)
                .object(record)
                .execute::<()>()
                .await;
            match result {
                Ok(_) => {
                    debug!(
                        "Firestore: saved simulation run {} successfully",
                        record.run_id
                    );
                    Ok(())
                }
                Err(e) => {
                    error!(
                        "Firestore: failed to save simulation run {}: {}",
                        record.run_id, e
                    );
                    Err(FirestoreError::WriteError(e.to_string()))
                }
            }
        }
    }
}
