//! # Name Generation Tables Module
//!
//! This module provides random name generation for various astronomical bodies
//! in the Traveller universe. It contains curated lists of thematic names and
//! functions to randomly select from them, ensuring consistent and immersive
//! naming throughout generated solar systems.
//!
//! ## Key Features
//!
//! - **Planet Names**: Science fiction themed names for worlds and gas giants
//! - **Star System Names**: Astronomical and mythological names for star systems
//! - **Moon Names**: Classical and mythological names for satellite bodies
//! - **Random Selection**: Thread-safe random generation using the `rand` crate
//!
//! ## Usage
//!
//! ```rust
//! # use worldgen::systems::name_tables::{gen_planet_name, gen_star_system_name, gen_moon_name};
//! let planet = gen_planet_name();        // "Kepler's Keep"
//! let system = gen_star_system_name();   // "Aegis Prime"
//! let moon = gen_moon_name();            // "Ganymede"
//! ```
//!
//! ## Thread Safety
//!
//! All generation functions use `rand::rng()` which provides thread-local
//! random number generation, making them safe for concurrent use across
//! multiple threads during system generation.

use rand::Rng;

/// Generates a random moon name
///
/// Selects from a comprehensive list of classical mythology and real
/// astronomical body names. Includes names from Greek, Roman, Norse,
/// and other mythological traditions, as well as real moons from
/// our solar system.
///
/// # Returns
///
/// A randomly selected moon name as a `String`
///
/// # Examples
///
/// ```rust,ignore
/// # use worldgen::systems::name_tables::gen_moon_name;
/// let name = gen_moon_name();
/// // Possible results: "Luna", "Phobos", "Europa"
/// ```
pub fn gen_moon_name() -> String {
    MOON_NAMES[rand::rng().random_range(0..MOON_NAMES.len())].to_string()
}

/// Generates a random planet name
///
/// Selects from a curated list of science fiction themed names suitable
/// for worlds and gas giants. Names evoke themes of exploration, technology,
/// and distant frontiers.
///
/// # Returns
///
/// A randomly selected planet name as a `String`
///
/// # Examples
///
/// ```rust,ignore
/// # use worldgen::systems::name_tables::gen_planet_name;
/// let name = gen_planet_name();
/// // Possible results: "Kepler's Keep", "Nova Nexus", "Quantum Quasar"
/// ```
pub fn gen_planet_name() -> String {
    PLANET_NAMES[rand::rng().random_range(0..PLANET_NAMES.len())].to_string()
}

/// Generates a random star system name
///
/// Selects from a list of astronomical and mythological names that combine
/// stellar phenomena with evocative descriptors. Names typically follow
/// patterns like "Constellation Feature" or "Star Descriptor".
///
/// # Returns
///
/// A randomly selected star system name as a `String`
///
/// # Examples
///
/// ```rust,ignore
/// # use worldgen::systems::name_tables::gen_star_system_name;
/// let name = gen_star_system_name();
/// // Possible results: "Aegis Prime", "Orion's Forge", "Vega Void"
/// ```
pub fn gen_star_system_name() -> String {
    STAR_SYSTEM_NAMES[rand::rng().random_range(0..STAR_SYSTEM_NAMES.len())].to_string()
}

/// Star system names combining astronomical terms with evocative descriptors
///
/// A curated collection of 100 names that evoke the grandeur and mystery
/// of space exploration. Names often reference real constellations,
/// stellar phenomena, and astronomical concepts while maintaining
/// a sense of adventure and discovery.
///
/// ## Naming Patterns
///
/// - **Constellation + Feature**: "Orion's Forge", "Cassiopeia Cluster"
/// - **Star + Descriptor**: "Rigel Rift", "Vega Void"
/// - **Phenomenon + Location**: "Nova Nexus", "Quantum Quasar"
/// - **Mythological + Space**: "Aegis Prime", "Nemesis Nexus"
const STAR_SYSTEM_NAMES: [&str; 100] = [
    "Aegis Prime",
    "Bellatrix Nebula",
    "Cygnus Reach",
    "Draco's Claw",
    "Eridanus Expanse",
    "Fornax Frontier",
    "Gliese",
    "Hydra's Heart",
    "Ixion Corridor",
    "Juno's Veil",
    "Kepler's Keep",
    "Lyra's Light",
    "Mizar Maze",
    "Nova Nexus",
    "Orion's Forge",
    "Polaris Point",
    "Quantum Quasar",
    "Rigel Rift",
    "Sirius Sector",
    "Taurus Tides",
    "Ursa Ultima",
    "Vega Void",
    "Wolf's Wisp",
    "Xena Crossroads",
    "Yggdrasil Yard",
    "Zenith Zone",
    "Altair Abyss",
    "Betelgeuse Beacon",
    "Cassiopeia Cluster",
    "Deneb Depths",
    "Epsilon Enigma",
    "Fomalhaut Fringes",
    "Gemini Gates",
    "Hercules Haven",
    "Io Isthmus",
    "Jupiter's Jewel",
    "Kochab Keystone",
    "Leo's Lair",
    "Merak Mists",
    "Nemesis Nexus",
    "Oberon Oasis",
    "Procyon Passage",
    "Quintessa",
    "Regulus Reach",
    "Spica Spiral",
    "Theta Threshold",
    "Umbra Utopia",
    "Virgo Venture",
    "Wezen Warp",
    "Xanadu Xing",
    "Yakima Yards",
    "Zosma Zone",
    "Andromeda Anchorage",
    "Boötes Borderlands",
    "Canis Corridor",
    "Dorado Dominion",
    "Eridanus Expanse",
    "Fornax Frontier",
    "Grus Gateway",
    "Hydrus Horizon",
    "Indus Inlet",
    "Lacerta Labyrinth",
    "Mensa Meridian",
    "Norma Nebula",
    "Octans Odyssey",
    "Pavo Paradise",
    "Reticulum Realm",
    "Sagitta Sanctuary",
    "Tucana Traverse",
    "Ursa Utopia",
    "Vela Voyage",
    "Volans Vista",
    "Vulpecula Valley",
    "Carina Crossroads",
    "Centaurus Citadel",
    "Cetus Confluence",
    "Chamaeleon Channel",
    "Columba Colony",
    "Corvus Crest",
    "Crater Cradle",
    "Crux Crucible",
    "Delphinus Delta",
    "Dorado Domain",
    "Draco Drifts",
    "Equuleus Equator",
    "Hercules Hinterlands",
    "Horologium Halo",
    "Hydra Highlands",
    "Indus Inlet",
    "Lepus Leap",
    "Lupus Labyrinth",
    "Lynx Ledge",
    "Microscopium Maze",
    "Monoceros Meadow",
    "Musca Mists",
    "Ophiuchus Orbit",
    "Pegasus Passage",
    "Phoenix Frontier",
    "Pictor Plateau",
    "Pisces Pools",
];

/// Moon and satellite names from classical mythology and astronomy
///
/// A comprehensive collection of 338+ names drawn from various sources:
/// - **Real Moons**: Names of actual moons in our solar system
/// - **Greek Mythology**: Classical names from Greek pantheon
/// - **Roman Mythology**: Roman equivalents and unique names
/// - **Norse Mythology**: Names from Scandinavian traditions
/// - **Astronomical Objects**: Names of asteroids, dwarf planets, and other bodies
///
/// ## Name Categories
///
/// - **Major Moons**: Well-known names like "Ganymede", "Titan", "Europa"
/// - **Minor Moons**: Lesser-known but real astronomical names
/// - **Mythological**: Classical names from various pantheons
/// - **Descriptive**: Names that evoke lunar or celestial qualities
///
/// Names are suitable for any type of satellite, from small rocky moons
/// to large satellite worlds with their own atmospheres and populations.
const MOON_NAMES: [&str; 338] = [
    "Aether",
    "Borealis",
    "Calypso",
    "Deimos",
    "Echo",
    "Frostbite",
    "Ganymede",
    "Hyperion",
    "Io",
    "Janus",
    "Kerberos",
    "Luna",
    "Mimas",
    "Nix",
    "Oberon",
    "Phobos",
    "Quaoar",
    "Rhea",
    "Styx",
    "Titan",
    "Umbriel",
    "Vesta",
    "Wyvern",
    "Xena",
    "Ymir",
    "Zephyr",
    "Aegaeon",
    "Belinda",
    "Charon",
    "Dione",
    "Europa",
    "Fenrir",
    "Galatea",
    "Hydra",
    "Iapetus",
    "Juliet",
    "Kale",
    "Larissa",
    "Miranda",
    "Naiad",
    "Ophelia",
    "Pandora",
    "Quincy",
    "Rosalind",
    "Sedna",
    "Tethys",
    "Uranus",
    "Vanth",
    "Weywot",
    "Xanthus",
    "Yalode",
    "Zelinda",
    "Adrastea",
    "Bianca",
    "Callisto",
    "Despina",
    "Elara",
    "Fenrir",
    "Galatea",
    "Halimede",
    "Isonoe",
    "Japet",
    "Kari",
    "Leda",
    "Metis",
    "Neso",
    "Orthosie",
    "Pasiphae",
    "Qilin",
    "Rhea",
    "Sinope",
    "Thebe",
    "Umbiel",
    "Valetudo",
    "Wanda",
    "Xerxes",
    "Ymir",
    "Zoe",
    "Ananke",
    "Bellatrix",
    "Carme",
    "Dysnomia",
    "Erinome",
    "Fjorgyn",
    "Gaspra",
    "Herse",
    "Iocaste",
    "Jarnsaxa",
    "Kallichore",
    "Lysithea",
    "Megaclite",
    "Nix",
    "Orius",
    "Praxidike",
    "Quetzal",
    "Rhadamanthys",
    "Sponde",
    "Taygete",
    "Ursula",
    "Valeska",
    "Wezen",
    "Xolotl",
    "Yvaga",
    "Zircon",
    "Aoede",
    "Beira",
    "Cyllene",
    "Daphnis",
    "Euanthe",
    "Fenrir",
    "Greip",
    "Hati",
    "Ijiraq",
    "Janus",
    "Kiviuq",
    "Loge",
    "Mundilfari",
    "Narvi",
    "Odin",
    "Pallene",
    "Quaoar",
    "Ravn",
    "Skoll",
    "Thrymr",
    "Ull",
    "Vidarr",
    "Waldron",
    "Xena",
    "Ymir",
    "Zephyr",
    "Albiorix",
    "Bestla",
    "Callirrhoe",
    "Daphnis",
    "Erriapus",
    "Farbauti",
    "Gerd",
    "Hyrrokkin",
    "Idunn",
    "Jarnsaxa",
    "Kari",
    "Loge",
    "Mimas",
    "Narvi",
    "Odin",
    "Paaliaq",
    "Quaoar",
    "Rhea",
    "Skadi",
    "Tarvos",
    "Ull",
    "Vali",
    "Wezen",
    "Xena",
    "Ymir",
    "Zephyr",
    "Aegir",
    "Bebhionn",
    "Carpo",
    "Dia",
    "Erinome",
    "Fornjot",
    "Geirrod",
    "Hati",
    "Ijiraq",
    "Janus",
    "Kale",
    "Leda",
    "Methone",
    "Neso",
    "Orthosie",
    "Pallene",
    "Quaoar",
    "Rhadamanthys",
    "Siarnaq",
    "Tethys",
    "Uranus",
    "Valeska",
    "Wanda",
    "Xolotl",
    "Yvaga",
    "Zircon",
    "Anthe",
    "Bergelmir",
    "Carme",
    "Dione",
    "Eukelade",
    "Fenrir",
    "Greip",
    "Helene",
    "Iocaste",
    "Jarnsaxa",
    "Kiviuq",
    "Lysithea",
    "Megaclite",
    "Nix",
    "Orius",
    "Praxidike",
    "Quetzal",
    "Rhea",
    "Sponde",
    "Taygete",
    "Ursula",
    "Valeska",
    "Wezen",
    "Xolotl",
    "Yvaga",
    "Zircon",
    "Aoede",
    "Beira",
    "Cyllene",
    "Daphnis",
    "Euanthe",
    "Fenrir",
    "Greip",
    "Hati",
    "Ijiraq",
    "Janus",
    "Kiviuq",
    "Loge",
    "Mundilfari",
    "Narvi",
    "Odin",
    "Pallene",
    "Quaoar",
    "Ravn",
    "Skoll",
    "Thrymr",
    "Ull",
    "Vidarr",
    "Waldron",
    "Xena",
    "Ymir",
    "Zephyr",
    "Albiorix",
    "Bestla",
    "Callirrhoe",
    "Daphnis",
    "Erriapus",
    "Farbauti",
    "Gerd",
    "Hyrrokkin",
    "Idunn",
    "Jarnsaxa",
    "Kari",
    "Loge",
    "Mimas",
    "Narvi",
    "Odin",
    "Paaliaq",
    "Quaoar",
    "Rhea",
    "Skadi",
    "Tarvos",
    "Ull",
    "Vali",
    "Wezen",
    "Xena",
    "Ymir",
    "Zephyr",
    "Aegir",
    "Bebhionn",
    "Carpo",
    "Dia",
    "Erinome",
    "Fornjot",
    "Geirrod",
    "Hati",
    "Ijiraq",
    "Janus",
    "Kale",
    "Leda",
    "Methone",
    "Neso",
    "Orthosie",
    "Pallene",
    "Quaoar",
    "Rhadamanthys",
    "Siarnaq",
    "Tethys",
    "Uranus",
    "Valeska",
    "Wanda",
    "Xolotl",
    "Yvaga",
    "Zircon",
    "Anthe",
    "Bergelmir",
    "Carme",
    "Dione",
    "Eukelade",
    "Fenrir",
    "Greip",
    "Helene",
    "Iocaste",
    "Jarnsaxa",
    "Kiviuq",
    "Lysithea",
    "Megaclite",
    "Nix",
    "Orius",
    "Praxidike",
    "Quetzal",
    "Rhea",
    "Sponde",
    "Taygete",
    "Ursula",
    "Valeska",
    "Wezen",
    "Xolotl",
    "Yvaga",
    "Zircon",
    "Aoede",
    "Beira",
    "Cyllene",
    "Daphnis",
    "Euanthe",
    "Fenrir",
    "Greip",
    "Hati",
    "Ijiraq",
    "Janus",
    "Kiviuq",
    "Loge",
    "Mundilfari",
    "Narvi",
    "Odin",
    "Pallene",
    "Quaoar",
    "Ravn",
    "Skoll",
    "Thrymr",
    "Ull",
    "Vidarr",
    "Waldron",
    "Xena",
    "Ymir",
    "Zephyr",
];

/// Planet names with science fiction and space exploration themes
///
/// A collection of evocative names suitable for worlds and gas giants.
/// Names are designed to sound futuristic and adventurous while
/// maintaining pronounceability and memorability.
///
/// ## Naming Themes
///
/// - **Astronomical**: References to stars, phenomena, and exploration
/// - **Technological**: Evokes advanced civilizations and space travel
/// - **Mythological**: Classical references adapted for space settings
/// - **Descriptive**: Names that suggest planetary characteristics
///
/// These names are used for significant worlds that warrant proper names
/// rather than systematic designations (e.g., populated gas giant systems).
const PLANET_NAMES: [&str; 400] = [
    "Zephyria",
    "Novacron",
    "Lumina",
    "Aethoria",
    "Celestis",
    "Thalassia",
    "Chronos",
    "Nebulos",
    "Helixia",
    "Quasar",
    "Vortexia",
    "Stellaris",
    "Novalux",
    "Astralis",
    "Galaxia",
    "Pulsara",
    "Cosmora",
    "Novastra",
    "Solara",
    "Lunara",
    "Auroris",
    "Nebulox",
    "Heliosia",
    "Quantara",
    "Novatron",
    "Stellara",
    "Pulsaris",
    "Galaxara",
    "Chronara",
    "Vortexis",
    "Aetheron",
    "Celestara",
    "Thalassos",
    "Novastria",
    "Luminara",
    "Nebulon",
    "Helixara",
    "Quasara",
    "Stellarix",
    "Pulsaron",
    "Galaxora",
    "Chronosia",
    "Vortexara",
    "Aethorix",
    "Celestron",
    "Thalassara",
    "Novastra",
    "Luminaris",
    "Nebulara",
    "Helixion",
    "Quasaris",
    "Stellaron",
    "Pulsaria",
    "Galaxion",
    "Chronara",
    "Vortexion",
    "Aethoron",
    "Celestara",
    "Thalassion",
    "Novastron",
    "Luminara",
    "Nebuloris",
    "Helixara",
    "Quasaron",
    "Stellaris",
    "Pulsarion",
    "Galaxara",
    "Chronorix",
    "Vortexara",
    "Aethoris",
    "Celestris",
    "Thalassara",
    "Novastris",
    "Luminaris",
    "Nebularis",
    "Helixoris",
    "Quasaris",
    "Stellaron",
    "Pulsara",
    "Galaxoris",
    "Chronara",
    "Vortexaris",
    "Aethoron",
    "Celestara",
    "Thalassion",
    "Novastron",
    "Luminara",
    "Nebuloris",
    "Helixara",
    "Quasaron",
    "Stellaris",
    "Pulsarion",
    "Galaxara",
    "Chronorix",
    "Vortexara",
    "Aethoris",
    "Celestris",
    "Thalassara",
    "Novastris",
    "Luminaris",
    "Zephyros",
    "Novacrys",
    "Luminos",
    "Aethoros",
    "Celestos",
    "Thalassos",
    "Chronos",
    "Nebulos",
    "Helixos",
    "Quasaros",
    "Vortexos",
    "Stellaros",
    "Novaluxos",
    "Astralos",
    "Galaxos",
    "Pulsaros",
    "Cosmoros",
    "Novastros",
    "Solaros",
    "Lunaros",
    "Auroros",
    "Nebuloxos",
    "Heliosios",
    "Quantaros",
    "Novatronos",
    "Stellaros",
    "Pulsaros",
    "Galaxaros",
    "Chronaros",
    "Vortexos",
    "Aetheronos",
    "Celestaros",
    "Thalassos",
    "Novastrios",
    "Luminaros",
    "Nebulonos",
    "Helixaros",
    "Quasaros",
    "Stellarixos",
    "Pulsaronos",
    "Galaxoros",
    "Chronosios",
    "Vortexaros",
    "Aethorixos",
    "Celestronos",
    "Thalassaros",
    "Novastros",
    "Luminaros",
    "Nebularos",
    "Helixionos",
    "Quasaris",
    "Stellaronos",
    "Pulsarios",
    "Galaxionos",
    "Chronaros",
    "Vortexionos",
    "Aethoronos",
    "Celestaros",
    "Thalassionos",
    "Novastronos",
    "Luminaros",
    "Nebuloris",
    "Helixaros",
    "Quasaronos",
    "Stellaris",
    "Pulsarionos",
    "Galaxaros",
    "Chronorixos",
    "Vortexaros",
    "Aethoris",
    "Celestris",
    "Thalassaros",
    "Novastris",
    "Luminaros",
    "Nebularis",
    "Helixoris",
    "Quasaris",
    "Stellaronos",
    "Pulsaros",
    "Galaxoris",
    "Chronaros",
    "Vortexaris",
    "Aethoronos",
    "Celestaros",
    "Thalassionos",
    "Novastronos",
    "Luminaros",
    "Nebuloris",
    "Helixaros",
    "Quasaronos",
    "Stellaris",
    "Pulsarionos",
    "Galaxaros",
    "Chronorixos",
    "Vortexaros",
    "Aethoris",
    "Celestris",
    "Thalassaros",
    "Novastris",
    "Luminaros",
    "Zephyria",
    "Novacronia",
    "Luminara",
    "Aethoria",
    "Celestia",
    "Thalassia",
    "Chronia",
    "Nebulia",
    "Helixia",
    "Quasaria",
    "Vortexia",
    "Stellaria",
    "Novaluxia",
    "Astralia",
    "Galaxia",
    "Pulsaria",
    "Cosmoria",
    "Novastria",
    "Solaria",
    "Lunaria",
    "Auroria",
    "Nebuloxia",
    "Heliosia",
    "Quantaria",
    "Novatronia",
    "Stellaria",
    "Pulsaria",
    "Galaxaria",
    "Chronia",
    "Vortexia",
    "Aetheronia",
    "Celestaria",
    "Thalassia",
    "Novastria",
    "Luminaria",
    "Nebulia",
    "Helixaria",
    "Quasaria",
    "Stellarixia",
    "Pulsaronia",
    "Galaxoria",
    "Chronosia",
    "Vortexaria",
    "Aethorixia",
    "Celestronia",
    "Thalassaria",
    "Novastria",
    "Luminaria",
    "Nebularia",
    "Helixionia",
    "Quasaria",
    "Stellaronia",
    "Pulsaria",
    "Galaxionia",
    "Chronaria",
    "Vortexionia",
    "Aethoronia",
    "Celestaria",
    "Thalassionia",
    "Novastronia",
    "Luminaria",
    "Nebuloris",
    "Helixaria",
    "Quasaronia",
    "Stellaria",
    "Pulsarionia",
    "Galaxaria",
    "Chronorixia",
    "Vortexaria",
    "Aethoria",
    "Celestria",
    "Thalassaria",
    "Novastria",
    "Luminaria",
    "Nebularia",
    "Helixoria",
    "Quasaria",
    "Stellaronia",
    "Pulsaria",
    "Galaxoria",
    "Chronaria",
    "Vortexaria",
    "Aethoronia",
    "Celestaria",
    "Thalassionia",
    "Novastronia",
    "Luminaria",
    "Nebuloris",
    "Helixaria",
    "Quasaronia",
    "Stellaria",
    "Pulsarionia",
    "Galaxaria",
    "Chronorixia",
    "Vortexaria",
    "Aethoria",
    "Celestria",
    "Thalassaria",
    "Novastria",
    "Luminaria",
    "Zephyron",
    "Novacron",
    "Luminon",
    "Aethoron",
    "Celeston",
    "Thalassion",
    "Chronon",
    "Nebulon",
    "Helixon",
    "Quasaron",
    "Vortexon",
    "Stellaron",
    "Novaluxon",
    "Astralon",
    "Galaxon",
    "Pulsaron",
    "Cosmoron",
    "Novastron",
    "Solaron",
    "Lunaron",
    "Auroron",
    "Nebuloxon",
    "Heliosion",
    "Quantaron",
    "Novatronon",
    "Stellaron",
    "Pulsaron",
    "Galaxaron",
    "Chronaron",
    "Vortexon",
    "Aetheron",
    "Celestaron",
    "Thalassion",
    "Novastrion",
    "Luminaron",
    "Nebulon",
    "Helixaron",
    "Quasaron",
    "Stellarixon",
    "Pulsaron",
    "Galaxoron",
    "Chronosion",
    "Vortexaron",
    "Aethorixon",
    "Celestronon",
    "Thalassaron",
    "Novastron",
    "Luminaron",
    "Nebularon",
    "Helixionon",
    "Quasaron",
    "Stellaron",
    "Pulsarion",
    "Galaxionon",
    "Chronaron",
    "Vortexionon",
    "Aethoron",
    "Celestaron",
    "Thalassionon",
    "Novastronon",
    "Luminaron",
    "Nebuloron",
    "Helixaron",
    "Quasaron",
    "Stellaron",
    "Pulsarionon",
    "Galaxaron",
    "Chronorixon",
    "Vortexaron",
    "Aethoron",
    "Celestron",
    "Thalassaron",
    "Novastron",
    "Luminaron",
    "Nebularon",
    "Helixoron",
    "Quasaron",
    "Stellaron",
    "Pulsaron",
    "Galaxoron",
    "Chronaron",
    "Vortexaron",
    "Aethoron",
    "Celestaron",
    "Thalassionon",
    "Novastronon",
    "Luminaron",
    "Nebuloron",
    "Helixaron",
    "Quasaron",
    "Stellaron",
    "Pulsarionon",
    "Galaxaron",
    "Chronorixon",
    "Vortexaron",
    "Aethoron",
    "Celestron",
    "Thalassaron",
    "Novastron",
    "Luminaron",
];
