//! Deterministic seed derivation for the public library API.
//!
//! The library's headline guarantee is "same seed → same image, forever".
//! For that to be useful to a consumer pulling worldgen in alongside a
//! TravellerMap query, the consumer needs a stable way to turn world
//! identity into the `u64` seed that `generate_system_png` /
//! `generate_planet_png` consume. That is what this module provides.
//!
//! Both helpers use SipHash-2-4 with a hardcoded key so the hash is stable
//! across `std` releases, target architectures, and worldgen versions.
//! **`DefaultHasher` is explicitly not used** — its algorithm is permitted
//! to change between Rust versions and would silently break determinism.
//!
//! If the hash recipe ever changes (key bytes, input order, normalization),
//! every system image generated by a downstream app will change too. Treat
//! the recipe as a versioned contract.

use siphasher::sip::SipHasher24;
use std::hash::Hasher;

/// SipHash-2-4 key, split into two `u64` halves. Chosen arbitrarily but
/// pinned forever — changing these bytes invalidates every seed any
/// consumer has cached.
const SIP_KEY_0: u64 = 0x736f_6c5f_7472_6176; // "sol_trav" little-endian
const SIP_KEY_1: u64 = 0x656c_6c65_725f_3030; // "eller_00" little-endian

fn new_hasher() -> SipHasher24 {
    SipHasher24::new_with_keys(SIP_KEY_0, SIP_KEY_1)
}

/// Derive a stable `u64` seed from TravellerMap-style world identity.
///
/// The hash recipe is:
/// 1. Lowercase + trim the sector name (so "Trojan Reach", "trojan reach",
///    and " Trojan Reach " all map to the same seed).
/// 2. Feed the normalized sector name, then `hex_x`, then `hex_y` to
///    SipHash-2-4 with a pinned key.
///
/// The output is suitable as the `seed: u64` parameter to
/// [`crate::generate_system_png`].
pub fn system_seed(sector: &str, hex_x: u8, hex_y: u8) -> u64 {
    let mut h = new_hasher();
    let normalized = sector.trim().to_lowercase();
    h.write(b"system_v1\0");
    h.write(normalized.as_bytes());
    h.write_u8(0);
    h.write_u8(hex_x);
    h.write_u8(hex_y);
    h.finish()
}

/// Derive a stable `u64` seed for a specific planet inside a system.
///
/// Takes the parent system's seed (from [`system_seed`]) plus a stable
/// identifier for the planet within that system (its orbit number and
/// name). Lowercases + trims the name for the same reason `system_seed`
/// normalizes the sector.
///
/// The output is suitable as the `seed: u64` parameter to
/// [`crate::generate_planet_png`].
pub fn planet_seed(system_seed: u64, planet_orbit: i32, planet_name: &str) -> u64 {
    let mut h = new_hasher();
    let normalized = planet_name.trim().to_lowercase();
    h.write(b"planet_v1\0");
    h.write_u64(system_seed);
    h.write_i32(planet_orbit);
    h.write(normalized.as_bytes());
    h.finish()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn system_seed_is_stable() {
        // Snapshot test — if the hash recipe ever changes, this fails
        // loudly so we know to bump a version marker and warn consumers.
        let s = system_seed("Trojan Reach", 31, 28);
        assert_eq!(s, 17167651877345473143_u64, "hash recipe changed; bump version");
    }

    #[test]
    fn system_seed_is_case_insensitive_on_sector() {
        let a = system_seed("Trojan Reach", 31, 28);
        let b = system_seed("trojan reach", 31, 28);
        let c = system_seed("  TROJAN REACH  ", 31, 28);
        assert_eq!(a, b);
        assert_eq!(a, c);
    }

    #[test]
    fn system_seed_varies_by_hex() {
        let a = system_seed("Trojan Reach", 31, 28);
        let b = system_seed("Trojan Reach", 31, 29);
        let c = system_seed("Trojan Reach", 32, 28);
        assert_ne!(a, b);
        assert_ne!(a, c);
        assert_ne!(b, c);
    }

    #[test]
    fn system_seed_varies_by_sector() {
        let a = system_seed("Trojan Reach", 31, 28);
        let b = system_seed("Spinward Marches", 31, 28);
        assert_ne!(a, b);
    }

    #[test]
    fn planet_seed_is_stable() {
        let sys = system_seed("Trojan Reach", 31, 28);
        let p = planet_seed(sys, 3, "Noricum");
        assert_eq!(p, 1901839566870135919_u64, "hash recipe changed; bump version");
    }

    #[test]
    fn planet_seed_varies_by_inputs() {
        let sys = system_seed("Trojan Reach", 31, 28);
        let base = planet_seed(sys, 3, "Noricum");
        let diff_orbit = planet_seed(sys, 4, "Noricum");
        let diff_name = planet_seed(sys, 3, "Aramis");
        let diff_sys = planet_seed(sys.wrapping_add(1), 3, "Noricum");
        assert_ne!(base, diff_orbit);
        assert_ne!(base, diff_name);
        assert_ne!(base, diff_sys);
    }

    #[test]
    fn planet_seed_name_is_case_insensitive() {
        let sys = system_seed("Trojan Reach", 31, 28);
        assert_eq!(
            planet_seed(sys, 3, "Noricum"),
            planet_seed(sys, 3, "noricum"),
        );
        assert_eq!(
            planet_seed(sys, 3, "Noricum"),
            planet_seed(sys, 3, "  NORICUM  "),
        );
    }
}
