//! # Trade State
//!
//! Shared state structure for synchronizing trade data between clients and server.

use serde::{Deserialize, Serialize};

use crate::systems::world::World;
use crate::trade::ZoneClassification;
use crate::trade::available_goods::AvailableGoodsTable;
use crate::trade::available_passengers::AvailablePassengers;
use crate::trade::ship_manifest::ShipManifest;

/// The synchronized trade state shared between all connected clients
///
/// World objects are sent from server to client after the server generates them.
/// Clients do NOT send World objects to the server - only name, UWP, coordinates, and zone.
/// The server generates World objects from these fields and sends them back.
/// This ensures the client and server always have the same World objects.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct TradeState {
    /// Version number for state compatibility
    pub version: u32,
    /// Origin world name (sent by client)
    pub origin_world_name: String,
    /// Origin world UWP (9-character code, sent by client)
    pub origin_uwp: String,
    /// Origin world galactic hex coordinates (from TravellerMap, sent by client)
    pub origin_coords: Option<(i32, i32)>,
    /// Origin world travel zone classification (sent by client)
    pub origin_zone: ZoneClassification,
    /// Origin World object (generated by server, sent back to client)
    pub origin_world: Option<World>,
    /// Destination world name (empty if no destination, sent by client)
    pub dest_world_name: String,
    /// Destination world UWP (empty if no destination, sent by client)
    pub dest_uwp: String,
    /// Destination world galactic hex coordinates (from TravellerMap, sent by client)
    pub dest_coords: Option<(i32, i32)>,
    /// Destination world travel zone classification (sent by client)
    pub dest_zone: ZoneClassification,
    /// Destination World object (generated by server, sent back to client)
    pub dest_world: Option<World>,
    /// Available goods at the origin
    pub available_goods: AvailableGoodsTable,
    /// Available passengers at the origin
    pub available_passengers: Option<AvailablePassengers>,
    /// Current ship manifest (selected goods, passengers, freight)
    pub ship_manifest: ShipManifest,
    /// Buyer's broker skill level
    pub buyer_broker_skill: i16,
    /// Seller's broker skill level
    pub seller_broker_skill: i16,
    /// Steward skill level (affects passenger recruitment)
    pub steward_skill: i16,
    /// Whether illegal goods are allowed
    pub illegal_goods: bool,
}
